// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type Customers struct {
	Customers []*User `json:"customers"`
	Cant      int     `json:"cant"`
}

type NewUser struct {
	CustomerName string `json:"customer_name"`
	Email        string `json:"email"`
	PhoneNumber  string `json:"phone_number"`
	Password     string `json:"password"`
}

type SeeData struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type UpdateUser struct {
	Email       string `bson:"email" json:"email"`
	PhoneNumber string `bson:"phone_number" json:"phone_number"`
	Password    string `bson:"password" json:"password"`
}

type User struct {
	ID           primitive.ObjectID `bson:"_id" json:"id,omitempty"` //`json:"_id"`
	CustomerName string             `bson:"customer_name" json:"customer_name"`
	Email        string             `bson:"email" json:"email"`
	PhoneNumber  string             `bson:"phone_number" json:"phone_number"`
	Password     string             `bson:"password" json:"password"`
	CreatedAt    time.Time          `bson:"created_at" json:"created_at"`
	UpdateAt     time.Time          `bson:"update_at" json:"update_at"`
}

type Users struct {
	TotaUser []*User `json:"totaUser"`
	Cant     int     `json:"cant"`
}
